### ISSUE TITLE
Not working :/

### ISSUE THREAD

**Issue by devingfx** [Daxiongmao87/Autogen-Studio-Docker#1]
Hi!

I naïvely just launched your docker image and I could figure out that the port is not mapped? So I config the default port mapping and a browse to http://localhost:8080/ just get nothing (ERR_CONNECTION_RESET) :/

Any investigation help? :)

Docker log:
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
```

Container details

<table class="table container-details-table ng-scope"><tbody><tr><td>Image</td><td><a ui-sref="docker.images.image({ id: container.Image, nodeName: nodeName })" class="ng-binding" href="https://localhost:9443/#!/2/docker/images/sha256%3A7159d798bc364e5cf47d7913221ba7611cecc76406ce976952a2de1a11dc38aa">daxiongmao87/autogen-studio-ui:latest@sha256:7159d798bc364e5cf47d7913221ba7611cecc76406ce976952a2de1a11dc38aa</a></td></tr><tr ng-if="portBindings.length &gt; 0" class="ng-scope"><td>Port configuration</td><td><div ng-repeat="portMapping in portBindings" class="ng-binding ng-scope">0.0.0.0:8080 <i class="fa fa-long-arrow-alt-right"></i>8080/tcp</div><div ng-repeat="portMapping in portBindings" class="ng-binding ng-scope">:::8080 <i class="fa fa-long-arrow-alt-right"></i>8080/tcp</div></td></tr><tr><td>CMD</td><td><code class="ng-binding">/bin/bash -c autogenstudio ui --port $AUTOGEN_PORT --host $AUTOGEN_HOST --workers $AUTOGEN_WORKERS</code></td></tr><tr><td>ENTRYPOINT</td><td><code class="ng-binding">null</code></td></tr><tr><td>ENV</td><td><table class="table table-bordered table-condensed"><tbody><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">AUTOGEN_HOST</td><td class="ng-binding">127.0.0.1</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">AUTOGEN_PORT</td><td class="ng-binding">8080</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">AUTOGEN_WORKERS</td><td class="ng-binding">1</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">GPG_KEY</td><td class="ng-binding">E3FF2839C048B25C084DEBE9B26995E310250568</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">LANG</td><td class="ng-binding">C.UTF-8</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PATH</td><td class="ng-binding">/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PYTHON_GET_PIP_SHA256</td><td class="ng-binding">dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PYTHON_GET_PIP_URL</td><td class="ng-binding">https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PYTHON_PIP_VERSION</td><td class="ng-binding">23.0.1</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PYTHON_SETUPTOOLS_VERSION</td><td class="ng-binding">65.5.1</td></tr><tr ng-repeat="var in container.Config.Env track by $index" class="ng-scope"><td class="ng-binding">PYTHON_VERSION</td><td class="ng-binding">3.10.14</td></tr></tbody></table></td></tr></tbody></table>

**Comment by Daxiongmao87** [comment]
Hey, yeah it got to a point where it just broke, I haven't been updating this as I moved on to other projects.  I apologize I have been so far removed from this project I don't think I'll be much help

**Comment by devingfx** [comment]
... sad :(

Could you please cleanup github / dockerhub / ??? for people to not loose time with dead bits, would be awesome! 

Thx to had tried tough!
